# file      : tests/basic/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : LGPLv2.1; see accompanying COPYING file

import libs = libmariadb%lib{mariadb}

exe{driver}: {h c}{*} $libs testscript
